
title: Sparks Bot
email: hello@simplymathematics.xyz
description:  # this means to ignore newlines until "baseurl:"
  A project page for Sparks Bot, the environmental monitoring robot.
baseurl: "/lab/" # the subpath of your site, e.g. /blog
url: "simplymathematics.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
